### ISSUE TITLE
Does it supports esp8266?

### ISSUE THREAD

**Issue by ESPboy-edu** [TMRh20/AutoAnalogAudio#27] opened 2021-11-17 18:53 UTC
Great library.
I would like to use it for ESPboy walkie-talkie NRF24 module for my www.espboy.com project 
but as i see it does not support esp8266

**Comment by 2bndy5** [comment] 2021-11-17 18:55
this a duplicate of #22

**Closed as completed** 2022-08-28 11:57 UTC
